### ISSUE TITLE
Is there any toturial doc for enodo?

### ISSUE THREAD

**Issue by eleleme** [SiriDB/siridb-enodo-hub#17]
Is there any tourial  for enodo quick start?

**Comment by timoj** [comment]
@eleleme We are working on the documentation, including a getting started section. I will update you as soon as we release this.

**Comment by timoj** [comment]
@eleleme We have published the first version of enodo docs. This will be updated and worked on continiously
https://siridb.github.io/siridb-enodo-docs/
